#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#various configuration tasks
~/bin/xrandr-set.sh #set up multi monitors
xset -b #disable keyboard beeps
setxkbmap -layout us -variant dvp # set up programmer dvorak
~/bin/clickpad.sh # thinkpad e540 clickpad settings
~/bin/naturalScroll.sh # touchpad natural 2 finger scrolling (horizontal and vertical)
wmname LG3D #fix for some java programs such as intellij and clion
nitrogen --restore #restore wallpaper

#autostart
~/bin/martybar.sh &
~/.config/bspwm/adjust_gaps.sh &
compton -cCGf --vsync opengl --shadow-exclude '!focused' &
